name: post_board
description: "Post Board"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  firebase_analytics: ^10.10.1
  firebase_crashlytics: ^3.5.1
  supabase_flutter: ^2.5.1
  easy_localization: ^3.0.7
  intl: ^0.19.0
  auto_route: ^8.0.3
  get_it: ^7.7.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  riverpod: ^2.5.0
  riverpod_annotation: ^2.3.4
  flutter_riverpod: ^2.4.10
  shared_preferences: ^2.2.3
  json_serializable: ^6.7.1
  url_launcher: ^6.2.6
  geolocator: ^12.0.0
  mask_text_input_formatter: ^2.9.0
  format: ^1.5.2
  connectivity_plus: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  auto_route_generator: ^8.0.0

flutter_launcher_icons:
  image_path_android: "assets/icons/android.png"
  image_path_ios: "assets/icons/ios.png"  
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icons/