name: post_board
description: 'Post Board'
publish_to: 'none'
version: 0.5.0+9

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.0.0
  firebase_analytics: ^11.0.0
  firebase_crashlytics: ^4.0.0
  supabase_flutter: ^2.5.1
  easy_localization: ^3.0.7
  intl: ^0.19.0
  auto_route: ^8.0.3
  get_it: ^7.7.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  riverpod: ^2.5.0
  riverpod_annotation: ^2.3.4
  flutter_riverpod: ^2.4.10
  shared_preferences: ^2.2.3
  json_serializable: ^6.7.1
  url_launcher: ^6.3.0
  geolocator: ^12.0.0
  mask_text_input_formatter: ^2.9.0
  format: ^1.5.2
  connectivity_plus: ^6.0.3
  share_plus: ^9.0.0
  in_app_review: ^2.0.9
  package_info_plus: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  auto_route_generator: ^8.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icons/